# Github action to build the Docker image
name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
        with:
          repository: 'buanet/docker.rpi-runner'

      - name: Prepare job
        run: |
          echo 'Lets go!'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
  
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: |
            linux/arm64
          tags: |
            buanet/rpi-runner:latest,